server:
  port: 8090

spring:
  kafka:
    client-id: address-generator
    group-id: address-generator-consumer-group
    bootstrap-servers: localhost:9091, localhost:9092, localhost:9093
    consumer:
      auto-offset-reset: earliest
kafka:
  topic:
    bank-accounts: bank-accounts-topic
    address-generator: address-generator-topic