server:
  port: 8090

spring:
  kafka:
    client-id: address-generator
    bootstrap-servers: 192.168.99.100:9092
    template:
      default-topic: bank-accounts-topic
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    group-id: address-generator-consumer
kafka:
  topic:
    input: bank-accounts-topic
    output: address-generator-topic
