server:
  port: 8098

spring:
  kafka:
    client-id: kafka-consumer-to-redis
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer-1
      auto-offset-reset: earliest
kafka:
  topic:
    bank-accounts: bank-accounts-topic
    address-generator: address-generator-topic