server:
  port: 8098

spring:
  kafka:
    client-id: kafka-consumer-to-redis
    group-id: consumer-redis-group
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      auto-offset-reset: earliest
kafka:
  topic:
    bank-accounts: bank-accounts-topic
    address-generator: address-generator-topic