server:
  port: 8888
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
    group-id: customers
  data:
    cassandra:
      contact-points: localhost
      keyspace-name: company