server:
  port: 8082

spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: bank_space
  kafka:
    client-id: consumer-kafka
    group-id: bank-account-and-address-consumer
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      auto-offset-reset: earliest
kafka:
  topic:
    bank-accounts: bank-accounts-topic
    address-generator: address-generator-topic