server:
  port: 8082

spring:
  data:
    cassandra:
      contact-points: 192.168.99.100
      port: 9042
      keyspace-name: bank_space
  kafka:
    client-id: consumer-kafka
    bootstrap-servers: 192.168.99.100:9092
    template:
      default-topic: bank-accounts-topic
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    group-id: bank-account-and-address-consumer
kafka:
  topic:
    bank-accounts: bank-accounts-topic
    address-generator: address-generator-topic